### Матричные разложения 

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)
 
print(A)
print(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -7.58790979e-16]]


In [ ]:
print(np.dot(Q, R))
print(np.dot(np.transpose(Q), Q))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1.00000000e+00 -2.48218629e-16 -2.62094065e-17]
 [-2.48218629e-16  1.00000000e+00  2.82872043e-17]
 [-2.62094065e-17  2.82872043e-17  1.00000000e+00]]


In [ ]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [ ]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  3.33066907e-15])

In [ ]:
X1 = np.linalg.solve(R1, B1)
X1

array([1.50000000e+00, 3.68219321e-15])

In [ ]:
X = np.append(X1, 0)
print (X)
np.linalg.norm(X)

[1.50000000e+00 3.68219321e-15 0.00000000e+00]


1.499999999999996

In [ ]:
np.linalg.norm(np.dot(A, X) - B)

1.2247448713915892

In [ ]:
X = np.array([1.5, 1, 0.5])
np.linalg.norm(X),  np.linalg.norm(np.dot(A, X) - B)

(1.8708286933869707, 2.449489742783178)