## Системы линейных алгебраических уравнений (СЛАУ) 

In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[2, 5, 1]])
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[1 2 3 2]
 [4 5 6 5]
 [7 8 9 1]]


(2, 3)

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[0, 0, 0]])
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]


(2, 2)

In [ ]:
A = np.array([[1, 1, 1], [1, 1, 2], [1, 1, 3]])
B = np.array([1, 1, 2])
np.linalg.matrix_rank(A, 0.0001)

2